/**
 * All 48 teams in the tournament (including eliminated ones).
 * Used for display purposes in the team history popup.
 */
export const allTeams: Record<string, { flag: string; name: string }> = {
  MEX: { flag: "🇲🇽", name: "Mexico" },
  RSA: { flag: "🇿🇦", name: "South Africa" },
  KOR: { flag: "🇰🇷", name: "South Korea" },
  CZE: { flag: "🇨🇿", name: "Czechia" },
  SUI: { flag: "🇨🇭", name: "Switzerland" },
  CAN: { flag: "🇨🇦", name: "Canada" },
  BIH: { flag: "🇧🇦", name: "Bosnia & Herz." },
  QAT: { flag: "🇶🇦", name: "Qatar" },
  BRA: { flag: "🇧🇷", name: "Brazil" },
  MAR: { flag: "🇲🇦", name: "Morocco" },
  SCO: { flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", name: "Scotland" },
  HAI: { flag: "🇭🇹", name: "Haiti" },
  USA: { flag: "🇺🇸", name: "United States" },
  AUS: { flag: "🇦🇺", name: "Australia" },
  PAR: { flag: "🇵🇾", name: "Paraguay" },
  TUR: { flag: "🇹🇷", name: "Turkey" },
  GER: { flag: "🇩🇪", name: "Germany" },
  CIV: { flag: "🇨🇮", name: "Ivory Coast" },
  ECU: { flag: "🇪🇨", name: "Ecuador" },
  CUW: { flag: "🇨🇼", name: "Curaçao" },
  NED: { flag: "🇳🇱", name: "Netherlands" },
  JPN: { flag: "🇯🇵", name: "Japan" },
  SWE: { flag: "🇸🇪", name: "Sweden" },
  TUN: { flag: "🇹🇳", name: "Tunisia" },
  BEL: { flag: "🇧🇪", name: "Belgium" },
  EGY: { flag: "🇪🇬", name: "Egypt" },
  IRN: { flag: "🇮🇷", name: "Iran" },
  NZL: { flag: "🇳🇿", name: "New Zealand" },
  ESP: { flag: "🇪🇸", name: "Spain" },
  CPV: { flag: "🇨🇻", name: "Cape Verde" },
  URU: { flag: "🇺🇾", name: "Uruguay" },
  KSA: { flag: "🇸🇦", name: "Saudi Arabia" },
  FRA: { flag: "🇫🇷", name: "France" },
  NOR: { flag: "🇳🇴", name: "Norway" },
  SEN: { flag: "🇸🇳", name: "Senegal" },
  IRQ: { flag: "🇮🇶", name: "Iraq" },
  ARG: { flag: "🇦🇷", name: "Argentina" },
  AUT: { flag: "🇦🇹", name: "Austria" },
  ALG: { flag: "🇩🇿", name: "Algeria" },
  JOR: { flag: "🇯🇴", name: "Jordan" },
  COL: { flag: "🇨🇴", name: "Colombia" },
  POR: { flag: "🇵🇹", name: "Portugal" },
  COD: { flag: "🇨🇩", name: "DR Congo" },
  UZB: { flag: "🇺🇿", name: "Uzbekistan" },
  ENG: { flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", name: "England" },
  CRO: { flag: "🇭🇷", name: "Croatia" },
  GHA: { flag: "🇬🇭", name: "Ghana" },
  PAN: { flag: "🇵🇦", name: "Panama" },
};
