export interface TeamDetail {
  code: string;
  name: string;
  flag: string;
  fifaRanking: number;
  confederation: string;
  coach: string;
  wcAppearances: number;
  bestFinish: string;
  wcRecord: { w: number; d: number; l: number };
  squad: { name: string; pos: "GK" | "DEF" | "MID" | "FWD"; club: string; num: number }[];
}

export const teamDetails: Record<string, TeamDetail> = {
  ARG: {
    code: "ARG", name: "Argentina", flag: "🇦🇷", fifaRanking: 1, confederation: "CONMEBOL",
    coach: "Lionel Scaloni", wcAppearances: 19, bestFinish: "Champions (1978, 1986, 2022)",
    wcRecord: { w: 47, d: 17, l: 24 },
    squad: [
      { name: "E. Martínez", pos: "GK", club: "Aston Villa", num: 23 },
      { name: "G. Rulli", pos: "GK", club: "Marseille", num: 12 },
      { name: "N. Molina", pos: "DEF", club: "Atlético Madrid", num: 26 },
      { name: "C. Romero", pos: "DEF", club: "Tottenham", num: 13 },
      { name: "L. Martínez Quarta", pos: "DEF", club: "River Plate", num: 6 },
      { name: "N. Otamendi", pos: "DEF", club: "Benfica", num: 19 },
      { name: "L. Paredes", pos: "MID", club: "Roma", num: 5 },
      { name: "R. De Paul", pos: "MID", club: "Atlético Madrid", num: 7 },
      { name: "E. Fernández", pos: "MID", club: "Chelsea", num: 24 },
      { name: "A. Mac Allister", pos: "MID", club: "Liverpool", num: 20 },
      { name: "G. Lo Celso", pos: "MID", club: "Real Betis", num: 18 },
      { name: "L. Messi", pos: "FWD", club: "Inter Miami", num: 10 },
      { name: "J. Álvarez", pos: "FWD", club: "Atlético Madrid", num: 9 },
      { name: "L. Martínez", pos: "FWD", club: "Inter Milan", num: 22 },
      { name: "Á. Di María", pos: "FWD", club: "Benfica", num: 11 },
      { name: "N. González", pos: "FWD", club: "Juventus", num: 15 },
    ],
  },
  ESP: {
    code: "ESP", name: "Spain", flag: "🇪🇸", fifaRanking: 2, confederation: "UEFA",
    coach: "Luis de la Fuente", wcAppearances: 17, bestFinish: "Champions (2010)",
    wcRecord: { w: 38, d: 18, l: 20 },
    squad: [
      { name: "U. Simón", pos: "GK", club: "Athletic Bilbao", num: 23 },
      { name: "D. Raya", pos: "GK", club: "Arsenal", num: 13 },
      { name: "D. Carvajal", pos: "DEF", club: "Real Madrid", num: 2 },
      { name: "R. Le Normand", pos: "DEF", club: "Atlético Madrid", num: 3 },
      { name: "A. Laporte", pos: "DEF", club: "Al-Nassr", num: 14 },
      { name: "M. Cucurella", pos: "DEF", club: "Chelsea", num: 24 },
      { name: "Rodri", pos: "MID", club: "Man City", num: 16 },
      { name: "Pedri", pos: "MID", club: "Barcelona", num: 8 },
      { name: "Gavi", pos: "MID", club: "Barcelona", num: 6 },
      { name: "D. Olmo", pos: "MID", club: "Barcelona", num: 10 },
      { name: "F. López", pos: "MID", club: "Barcelona", num: 17 },
      { name: "L. Yamal", pos: "FWD", club: "Barcelona", num: 19 },
      { name: "N. Williams", pos: "FWD", club: "Athletic Bilbao", num: 11 },
      { name: "Á. Morata", pos: "FWD", club: "AC Milan", num: 7 },
      { name: "Oyarzabal", pos: "FWD", club: "Real Sociedad", num: 21 },
    ],
  },
  FRA: {
    code: "FRA", name: "France", flag: "🇫🇷", fifaRanking: 3, confederation: "UEFA",
    coach: "Didier Deschamps", wcAppearances: 17, bestFinish: "Champions (1998, 2018)",
    wcRecord: { w: 40, d: 14, l: 20 },
    squad: [
      { name: "M. Maignan", pos: "GK", club: "AC Milan", num: 23 },
      { name: "J. Koundé", pos: "DEF", club: "Barcelona", num: 5 },
      { name: "W. Saliba", pos: "DEF", club: "Arsenal", num: 17 },
      { name: "D. Upamecano", pos: "DEF", club: "Bayern Munich", num: 4 },
      { name: "T. Hernández", pos: "DEF", club: "AC Milan", num: 22 },
      { name: "A. Tchouaméni", pos: "MID", club: "Real Madrid", num: 8 },
      { name: "N. Kanté", pos: "MID", club: "Al-Ittihad", num: 13 },
      { name: "A. Griezmann", pos: "MID", club: "Atlético Madrid", num: 7 },
      { name: "K. Mbappé", pos: "FWD", club: "Real Madrid", num: 10 },
      { name: "O. Dembélé", pos: "FWD", club: "PSG", num: 11 },
      { name: "R. Olise", pos: "FWD", club: "Bayern Munich", num: 14 },
      { name: "M. Thuram", pos: "FWD", club: "Inter Milan", num: 15 },
      { name: "B. Barcola", pos: "FWD", club: "PSG", num: 20 },
    ],
  },
  ENG: {
    code: "ENG", name: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", fifaRanking: 4, confederation: "UEFA",
    coach: "Thomas Tuchel", wcAppearances: 17, bestFinish: "Champions (1966)",
    wcRecord: { w: 32, d: 22, l: 17 },
    squad: [
      { name: "J. Pickford", pos: "GK", club: "Everton", num: 1 },
      { name: "K. Walker", pos: "DEF", club: "Man City", num: 2 },
      { name: "J. Stones", pos: "DEF", club: "Man City", num: 5 },
      { name: "M. Guéhi", pos: "DEF", club: "Crystal Palace", num: 6 },
      { name: "L. Shaw", pos: "DEF", club: "Man United", num: 3 },
      { name: "D. Rice", pos: "MID", club: "Arsenal", num: 4 },
      { name: "J. Bellingham", pos: "MID", club: "Real Madrid", num: 10 },
      { name: "P. Foden", pos: "MID", club: "Man City", num: 11 },
      { name: "B. Saka", pos: "FWD", club: "Arsenal", num: 7 },
      { name: "H. Kane", pos: "FWD", club: "Bayern Munich", num: 9 },
      { name: "C. Palmer", pos: "FWD", club: "Chelsea", num: 20 },
      { name: "A. Gordon", pos: "FWD", club: "Newcastle", num: 17 },
    ],
  },
  POR: {
    code: "POR", name: "Portugal", flag: "🇵🇹", fifaRanking: 5, confederation: "UEFA",
    coach: "Roberto Martínez", wcAppearances: 9, bestFinish: "3rd Place (1966)",
    wcRecord: { w: 21, d: 7, l: 12 },
    squad: [
      { name: "D. Costa", pos: "GK", club: "Porto", num: 22 },
      { name: "Rúben Dias", pos: "DEF", club: "Man City", num: 4 },
      { name: "Pepe", pos: "DEF", club: "Porto", num: 3 },
      { name: "N. Mendes", pos: "DEF", club: "PSG", num: 19 },
      { name: "J. Cancelo", pos: "DEF", club: "Barcelona", num: 20 },
      { name: "Vitinha", pos: "MID", club: "PSG", num: 8 },
      { name: "Bruno Fernandes", pos: "MID", club: "Man United", num: 10 },
      { name: "B. Silva", pos: "MID", club: "Man City", num: 11 },
      { name: "Cristiano Ronaldo", pos: "FWD", club: "Al-Nassr", num: 7 },
      { name: "R. Leão", pos: "FWD", club: "AC Milan", num: 17 },
      { name: "Pedro Neto", pos: "FWD", club: "Chelsea", num: 15 },
      { name: "Gonçalo Ramos", pos: "FWD", club: "PSG", num: 9 },
    ],
  },
  BRA: {
    code: "BRA", name: "Brazil", flag: "🇧🇷", fifaRanking: 6, confederation: "CONMEBOL",
    coach: "Dorival Júnior", wcAppearances: 23, bestFinish: "Champions (1958, 62, 70, 94, 2002)",
    wcRecord: { w: 76, d: 18, l: 19 },
    squad: [
      { name: "Alisson", pos: "GK", club: "Liverpool", num: 1 },
      { name: "Marquinhos", pos: "DEF", club: "PSG", num: 4 },
      { name: "G. Magalhães", pos: "DEF", club: "Arsenal", num: 16 },
      { name: "Militão", pos: "DEF", club: "Real Madrid", num: 14 },
      { name: "Danilo", pos: "DEF", club: "Juventus", num: 2 },
      { name: "B. Guimarães", pos: "MID", club: "Newcastle", num: 5 },
      { name: "Lucas Paquetá", pos: "MID", club: "West Ham", num: 8 },
      { name: "Vinícius Jr", pos: "FWD", club: "Real Madrid", num: 7 },
      { name: "Rodrygo", pos: "FWD", club: "Real Madrid", num: 11 },
      { name: "Raphinha", pos: "FWD", club: "Barcelona", num: 19 },
      { name: "Endrick", pos: "FWD", club: "Real Madrid", num: 9 },
      { name: "Savinho", pos: "FWD", club: "Man City", num: 20 },
    ],
  },
  MAR: {
    code: "MAR", name: "Morocco", flag: "🇲🇦", fifaRanking: 7, confederation: "CAF",
    coach: "Walid Regragui", wcAppearances: 7, bestFinish: "4th Place (2022)",
    wcRecord: { w: 7, d: 6, l: 8 },
    squad: [
      { name: "Y. Bounou", pos: "GK", club: "Al-Hilal", num: 1 },
      { name: "A. Hakimi", pos: "DEF", club: "PSG", num: 2 },
      { name: "N. Mazraoui", pos: "DEF", club: "Man United", num: 3 },
      { name: "N. Aguerd", pos: "DEF", club: "West Ham", num: 5 },
      { name: "S. Amrabat", pos: "MID", club: "Fiorentina", num: 4 },
      { name: "A. Ounahi", pos: "MID", club: "Marseille", num: 8 },
      { name: "H. Ziyech", pos: "MID", club: "Galatasaray", num: 7 },
      { name: "Y. En-Nesyri", pos: "FWD", club: "Fenerbahce", num: 19 },
      { name: "S. Boufal", pos: "FWD", club: "Al-Rayyan", num: 17 },
      { name: "B. El Khannouss", pos: "MID", club: "Leicester", num: 10 },
    ],
  },
  NED: {
    code: "NED", name: "Netherlands", flag: "🇳🇱", fifaRanking: 8, confederation: "UEFA",
    coach: "Ronald Koeman", wcAppearances: 11, bestFinish: "Runner-up (1974, 1978, 2010)",
    wcRecord: { w: 30, d: 13, l: 13 },
    squad: [
      { name: "B. Verbruggen", pos: "GK", club: "Brighton", num: 13 },
      { name: "V. van Dijk", pos: "DEF", club: "Liverpool", num: 4 },
      { name: "N. Aké", pos: "DEF", club: "Man City", num: 5 },
      { name: "D. Dumfries", pos: "DEF", club: "Inter Milan", num: 22 },
      { name: "F. de Jong", pos: "MID", club: "Barcelona", num: 21 },
      { name: "T. Reijnders", pos: "MID", club: "AC Milan", num: 14 },
      { name: "X. Simons", pos: "MID", club: "RB Leipzig", num: 10 },
      { name: "C. Gakpo", pos: "FWD", club: "Liverpool", num: 11 },
      { name: "M. Depay", pos: "FWD", club: "Corinthians", num: 9 },
      { name: "D. Malen", pos: "FWD", club: "Dortmund", num: 18 },
    ],
  },
  BEL: {
    code: "BEL", name: "Belgium", flag: "🇧🇪", fifaRanking: 9, confederation: "UEFA",
    coach: "Domenico Tedesco", wcAppearances: 14, bestFinish: "3rd Place (2018)",
    wcRecord: { w: 21, d: 11, l: 19 },
    squad: [
      { name: "K. Casteels", pos: "GK", club: "Wolfsburg", num: 1 },
      { name: "T. Meunier", pos: "DEF", club: "Trabzonspor", num: 15 },
      { name: "J. Vertonghen", pos: "DEF", club: "Anderlecht", num: 5 },
      { name: "A. Theate", pos: "DEF", club: "Rennes", num: 3 },
      { name: "K. De Bruyne", pos: "MID", club: "Man City", num: 7 },
      { name: "A. Onana", pos: "MID", club: "Aston Villa", num: 8 },
      { name: "Y. Tielemans", pos: "MID", club: "Aston Villa", num: 6 },
      { name: "J. Doku", pos: "FWD", club: "Man City", num: 11 },
      { name: "R. Lukaku", pos: "FWD", club: "Napoli", num: 9 },
      { name: "L. Trossard", pos: "FWD", club: "Arsenal", num: 14 },
    ],
  },
  GER: {
    code: "GER", name: "Germany", flag: "🇩🇪", fifaRanking: 10, confederation: "UEFA",
    coach: "Julian Nagelsmann", wcAppearances: 20, bestFinish: "Champions (1954, 74, 90, 2014)",
    wcRecord: { w: 70, d: 21, l: 22 },
    squad: [
      { name: "M. ter Stegen", pos: "GK", club: "Barcelona", num: 22 },
      { name: "A. Rüdiger", pos: "DEF", club: "Real Madrid", num: 2 },
      { name: "J. Tah", pos: "DEF", club: "Leverkusen", num: 4 },
      { name: "D. Raum", pos: "DEF", club: "RB Leipzig", num: 3 },
      { name: "J. Kimmich", pos: "MID", club: "Bayern Munich", num: 6 },
      { name: "T. Kroos", pos: "MID", club: "Retired", num: 8 },
      { name: "F. Wirtz", pos: "MID", club: "Leverkusen", num: 10 },
      { name: "J. Musiala", pos: "MID", club: "Bayern Munich", num: 14 },
      { name: "K. Havertz", pos: "FWD", club: "Arsenal", num: 7 },
      { name: "L. Sané", pos: "FWD", club: "Bayern Munich", num: 19 },
      { name: "N. Füllkrug", pos: "FWD", club: "West Ham", num: 9 },
    ],
  },
  CRO: {
    code: "CRO", name: "Croatia", flag: "🇭🇷", fifaRanking: 11, confederation: "UEFA",
    coach: "Zlatko Dalić", wcAppearances: 7, bestFinish: "Runner-up (2018)",
    wcRecord: { w: 16, d: 5, l: 9 },
    squad: [
      { name: "D. Livaković", pos: "GK", club: "Fenerbahce", num: 1 },
      { name: "J. Gvardiol", pos: "DEF", club: "Man City", num: 20 },
      { name: "D. Ćaleta-Car", pos: "DEF", club: "Lyon", num: 3 },
      { name: "L. Modrić", pos: "MID", club: "Real Madrid", num: 10 },
      { name: "M. Kovačić", pos: "MID", club: "Man City", num: 8 },
      { name: "M. Brozović", pos: "MID", club: "Al-Nassr", num: 11 },
      { name: "A. Kramarić", pos: "FWD", club: "Hoffenheim", num: 9 },
      { name: "B. Petković", pos: "FWD", club: "Dinamo Zagreb", num: 16 },
    ],
  },
  COL: {
    code: "COL", name: "Colombia", flag: "🇨🇴", fifaRanking: 13, confederation: "CONMEBOL",
    coach: "Néstor Lorenzo", wcAppearances: 7, bestFinish: "Quarter-finals (2014)",
    wcRecord: { w: 10, d: 5, l: 7 },
    squad: [
      { name: "D. Ospina", pos: "GK", club: "Al-Nassr", num: 1 },
      { name: "D. Sánchez", pos: "DEF", club: "Tottenham", num: 23 },
      { name: "J. Mojica", pos: "DEF", club: "Villarreal", num: 17 },
      { name: "J. Arias", pos: "MID", club: "Fluminense", num: 14 },
      { name: "R. Ríos", pos: "MID", club: "Palmeiras", num: 5 },
      { name: "J. Rodríguez", pos: "MID", club: "Rayo Vallecano", num: 10 },
      { name: "L. Díaz", pos: "FWD", club: "Liverpool", num: 7 },
      { name: "R. Durán", pos: "FWD", club: "Aston Villa", num: 9 },
      { name: "L. Sinisterra", pos: "FWD", club: "Bournemouth", num: 11 },
    ],
  },
  MEX: {
    code: "MEX", name: "Mexico", flag: "🇲🇽", fifaRanking: 14, confederation: "CONCACAF",
    coach: "Javier Aguirre", wcAppearances: 18, bestFinish: "Quarter-finals (1970, 1986)",
    wcRecord: { w: 18, d: 16, l: 27 },
    squad: [
      { name: "G. Ochoa", pos: "GK", club: "Salernitana", num: 13 },
      { name: "J. Sánchez", pos: "DEF", club: "Ajax", num: 4 },
      { name: "C. Montes", pos: "DEF", club: "Almería", num: 3 },
      { name: "E. Álvarez", pos: "MID", club: "West Ham", num: 5 },
      { name: "S. Giménez", pos: "FWD", club: "Feyenoord", num: 9 },
      { name: "H. Lozano", pos: "FWD", club: "PSV", num: 22 },
      { name: "A. Vega", pos: "MID", club: "Monterrey", num: 10 },
      { name: "O. Pineda", pos: "MID", club: "AEK Athens", num: 8 },
    ],
  },
  USA: {
    code: "USA", name: "United States", flag: "🇺🇸", fifaRanking: 17, confederation: "CONCACAF",
    coach: "Mauricio Pochettino", wcAppearances: 12, bestFinish: "3rd Place (1930)",
    wcRecord: { w: 10, d: 8, l: 15 },
    squad: [
      { name: "M. Turner", pos: "GK", club: "Nottingham Forest", num: 1 },
      { name: "S. Dest", pos: "DEF", club: "PSV", num: 2 },
      { name: "T. Ream", pos: "DEF", club: "Charlotte FC", num: 5 },
      { name: "C. Richards", pos: "DEF", club: "Crystal Palace", num: 15 },
      { name: "A. Robinson", pos: "DEF", club: "Fulham", num: 3 },
      { name: "W. McKennie", pos: "MID", club: "Juventus", num: 8 },
      { name: "T. Adams", pos: "MID", club: "Bournemouth", num: 4 },
      { name: "Y. Musah", pos: "MID", club: "AC Milan", num: 6 },
      { name: "G. Reyna", pos: "MID", club: "Dortmund", num: 7 },
      { name: "C. Pulisic", pos: "FWD", club: "AC Milan", num: 10 },
      { name: "T. Weah", pos: "FWD", club: "Juventus", num: 11 },
      { name: "F. Balogun", pos: "FWD", club: "Monaco", num: 9 },
    ],
  },
  JPN: {
    code: "JPN", name: "Japan", flag: "🇯🇵", fifaRanking: 18, confederation: "AFC",
    coach: "Hajime Moriyasu", wcAppearances: 8, bestFinish: "Round of 16 (2002, 2022)",
    wcRecord: { w: 8, d: 6, l: 12 },
    squad: [
      { name: "S. Suzuki", pos: "GK", club: "Freiburg", num: 12 },
      { name: "T. Tomiyasu", pos: "DEF", club: "Arsenal", num: 2 },
      { name: "K. Itakura", pos: "DEF", club: "Gladbach", num: 4 },
      { name: "W. Endo", pos: "MID", club: "Liverpool", num: 6 },
      { name: "T. Kubo", pos: "MID", club: "Real Sociedad", num: 11 },
      { name: "K. Mitoma", pos: "FWD", club: "Brighton", num: 9 },
      { name: "D. Kamada", pos: "MID", club: "Crystal Palace", num: 8 },
      { name: "A. Doan", pos: "FWD", club: "Freiburg", num: 21 },
    ],
  },
  SUI: {
    code: "SUI", name: "Switzerland", flag: "🇨🇭", fifaRanking: 19, confederation: "UEFA",
    coach: "Murat Yakın", wcAppearances: 13, bestFinish: "Quarter-finals (1934, 1938, 1954)",
    wcRecord: { w: 14, d: 9, l: 18 },
    squad: [
      { name: "Y. Sommer", pos: "GK", club: "Inter Milan", num: 1 },
      { name: "M. Akanji", pos: "DEF", club: "Man City", num: 5 },
      { name: "R. Rodríguez", pos: "DEF", club: "Real Betis", num: 13 },
      { name: "G. Xhaka", pos: "MID", club: "Leverkusen", num: 10 },
      { name: "D. Freuler", pos: "MID", club: "Bologna", num: 8 },
      { name: "R. Vargas", pos: "FWD", club: "Augsburg", num: 15 },
      { name: "B. Embolo", pos: "FWD", club: "Monaco", num: 7 },
      { name: "N. Okafor", pos: "FWD", club: "AC Milan", num: 17 },
    ],
  },
  ECU: {
    code: "ECU", name: "Ecuador", flag: "🇪🇨", fifaRanking: 23, confederation: "CONMEBOL",
    coach: "Sebastián Beccacece", wcAppearances: 5, bestFinish: "Round of 16 (2006)",
    wcRecord: { w: 4, d: 3, l: 6 },
    squad: [
      { name: "H. Galíndez", pos: "GK", club: "Aucas", num: 1 },
      { name: "P. Hincapié", pos: "DEF", club: "Leverkusen", num: 3 },
      { name: "M. Caicedo", pos: "MID", club: "Chelsea", num: 23 },
      { name: "K. Páez", pos: "MID", club: "Independiente del Valle", num: 10 },
      { name: "E. Valencia", pos: "FWD", club: "Liga de Quito", num: 13 },
      { name: "G. Plata", pos: "FWD", club: "Al-Sadd", num: 20 },
    ],
  },
  AUT: {
    code: "AUT", name: "Austria", flag: "🇦🇹", fifaRanking: 24, confederation: "UEFA",
    coach: "Ralf Rangnick", wcAppearances: 8, bestFinish: "3rd Place (1954)",
    wcRecord: { w: 12, d: 4, l: 10 },
    squad: [
      { name: "P. Pentz", pos: "GK", club: "Brøndby", num: 13 },
      { name: "K. Laimer", pos: "MID", club: "Bayern Munich", num: 8 },
      { name: "M. Sabitzer", pos: "MID", club: "Dortmund", num: 9 },
      { name: "F. Grillitsch", pos: "MID", club: "Hoffenheim", num: 6 },
      { name: "C. Baumgartner", pos: "MID", club: "RB Leipzig", num: 14 },
      { name: "M. Arnautović", pos: "FWD", club: "Inter Milan", num: 7 },
    ],
  },
  AUS: {
    code: "AUS", name: "Australia", flag: "🇦🇺", fifaRanking: 27, confederation: "AFC",
    coach: "Tony Popovic", wcAppearances: 7, bestFinish: "Round of 16 (2006, 2022)",
    wcRecord: { w: 4, d: 5, l: 10 },
    squad: [
      { name: "M. Ryan", pos: "GK", club: "Roma", num: 1 },
      { name: "H. Souttar", pos: "DEF", club: "Sheffield United", num: 4 },
      { name: "A. Hrustic", pos: "MID", club: "Real Valladolid", num: 10 },
      { name: "J. Irvine", pos: "MID", club: "St Pauli", num: 8 },
      { name: "C. Goodwin", pos: "FWD", club: "Al-Wehda", num: 17 },
      { name: "M. Duke", pos: "FWD", club: "Machida Zelvia", num: 9 },
    ],
  },
  ALG: {
    code: "ALG", name: "Algeria", flag: "🇩🇿", fifaRanking: 28, confederation: "CAF",
    coach: "Vladimir Petković", wcAppearances: 5, bestFinish: "Round of 16 (2014)",
    wcRecord: { w: 3, d: 5, l: 5 },
    squad: [
      { name: "R. M'Bolhi", pos: "GK", club: "Al-Ettifaq", num: 23 },
      { name: "R. Aït-Nouri", pos: "DEF", club: "Wolves", num: 3 },
      { name: "I. Bennacer", pos: "MID", club: "AC Milan", num: 8 },
      { name: "S. Atal", pos: "MID", club: "Nice", num: 2 },
      { name: "S. Feghouli", pos: "MID", club: "Chabab Belouizdad", num: 10 },
      { name: "A. Gouiri", pos: "FWD", club: "Rennes", num: 9 },
    ],
  },
  EGY: {
    code: "EGY", name: "Egypt", flag: "🇪🇬", fifaRanking: 29, confederation: "CAF",
    coach: "Hassan Shehata II", wcAppearances: 4, bestFinish: "Group Stage (1934, 1990, 2018)",
    wcRecord: { w: 2, d: 1, l: 5 },
    squad: [
      { name: "M. El-Shenawy", pos: "GK", club: "Al Ahly", num: 1 },
      { name: "O. Kamal", pos: "DEF", club: "Al Ahly", num: 4 },
      { name: "M. Salah", pos: "FWD", club: "Liverpool", num: 10 },
      { name: "O. Marmoush", pos: "FWD", club: "Eintracht Frankfurt", num: 7 },
      { name: "T. Hamed", pos: "MID", club: "Al Ahly", num: 6 },
      { name: "M. Trezeguet", pos: "FWD", club: "Trabzonspor", num: 14 },
    ],
  },
  CAN: {
    code: "CAN", name: "Canada", flag: "🇨🇦", fifaRanking: 30, confederation: "CONCACAF",
    coach: "Jesse Marsch", wcAppearances: 3, bestFinish: "Round of 32 (2026)",
    wcRecord: { w: 2, d: 2, l: 2 },
    squad: [
      { name: "M. Crépeau", pos: "GK", club: "Portland Timbers", num: 16 },
      { name: "A. Davies", pos: "DEF", club: "Bayern Munich", num: 19 },
      { name: "A. Johnston", pos: "DEF", club: "Celtic", num: 2 },
      { name: "S. Eustáquio", pos: "MID", club: "Porto", num: 7 },
      { name: "T. Buchanan", pos: "MID", club: "Inter Milan", num: 11 },
      { name: "J. David", pos: "FWD", club: "Lille", num: 9 },
      { name: "C. Larin", pos: "FWD", club: "Real Valladolid", num: 17 },
    ],
  },
  NOR: {
    code: "NOR", name: "Norway", flag: "🇳🇴", fifaRanking: 31, confederation: "UEFA",
    coach: "Ståle Solbakken", wcAppearances: 4, bestFinish: "Group Stage",
    wcRecord: { w: 2, d: 3, l: 6 },
    squad: [
      { name: "Ø. Nyland", pos: "GK", club: "Sevilla", num: 1 },
      { name: "K. Ajer", pos: "DEF", club: "Brentford", num: 5 },
      { name: "M. Ødegaard", pos: "MID", club: "Arsenal", num: 10 },
      { name: "S. Berge", pos: "MID", club: "Fulham", num: 8 },
      { name: "E. Haaland", pos: "FWD", club: "Man City", num: 9 },
      { name: "A. Sørloth", pos: "FWD", club: "Atlético Madrid", num: 11 },
    ],
  },
  CIV: {
    code: "CIV", name: "Ivory Coast", flag: "🇨🇮", fifaRanking: 33, confederation: "CAF",
    coach: "Emerse Faé", wcAppearances: 4, bestFinish: "Group Stage",
    wcRecord: { w: 3, d: 4, l: 5 },
    squad: [
      { name: "B. Sangaré", pos: "GK", club: "Lens", num: 16 },
      { name: "S. Aurier", pos: "DEF", club: "Galatasaray", num: 2 },
      { name: "F. Kessié", pos: "MID", club: "Al-Ahli", num: 8 },
      { name: "I. Sangaré", pos: "MID", club: "Feyenoord", num: 6 },
      { name: "N. Pépé", pos: "FWD", club: "Villarreal", num: 11 },
      { name: "S. Haller", pos: "FWD", club: "Dortmund", num: 9 },
    ],
  },
  SWE: {
    code: "SWE", name: "Sweden", flag: "🇸🇪", fifaRanking: 38, confederation: "UEFA",
    coach: "Jon Dahl Tomasson", wcAppearances: 13, bestFinish: "Runner-up (1958)",
    wcRecord: { w: 20, d: 13, l: 17 },
    squad: [
      { name: "R. Olsen", pos: "GK", club: "Aston Villa", num: 1 },
      { name: "V. Lindelöf", pos: "DEF", club: "Man United", num: 3 },
      { name: "A. Isak", pos: "FWD", club: "Newcastle", num: 11 },
      { name: "D. Kulusevski", pos: "FWD", club: "Tottenham", num: 10 },
      { name: "V. Gyökeres", pos: "FWD", club: "Sporting CP", num: 9 },
      { name: "E. Forsberg", pos: "MID", club: "New York Red Bulls", num: 10 },
    ],
  },
  PAR: {
    code: "PAR", name: "Paraguay", flag: "🇵🇾", fifaRanking: 41, confederation: "CONMEBOL",
    coach: "Alfaro", wcAppearances: 9, bestFinish: "Quarter-finals (2010)",
    wcRecord: { w: 7, d: 10, l: 10 },
    squad: [
      { name: "A. Silva", pos: "GK", club: "Celta Vigo", num: 1 },
      { name: "G. Gómez", pos: "DEF", club: "Palmeiras", num: 2 },
      { name: "M. Almirón", pos: "MID", club: "Newcastle", num: 10 },
      { name: "A. Enciso", pos: "FWD", club: "Brighton", num: 24 },
      { name: "J. Sanabria", pos: "FWD", club: "Torino", num: 9 },
    ],
  },
  SEN: {
    code: "SEN", name: "Senegal", flag: "🇸🇳", fifaRanking: 15, confederation: "CAF",
    coach: "Pape Thiaw", wcAppearances: 4, bestFinish: "Quarter-finals (2002)",
    wcRecord: { w: 5, d: 5, l: 4 },
    squad: [
      { name: "É. Mendy", pos: "GK", club: "Al-Ahli", num: 1 },
      { name: "K. Koulibaly", pos: "DEF", club: "Al-Hilal", num: 3 },
      { name: "I. Gueye", pos: "MID", club: "Everton", num: 5 },
      { name: "P. Gueye", pos: "MID", club: "Inter Milan", num: 8 },
      { name: "S. Mané", pos: "FWD", club: "Al-Nassr", num: 10 },
      { name: "N. Jackson", pos: "FWD", club: "Chelsea", num: 9 },
    ],
  },
  COD: {
    code: "COD", name: "DR Congo", flag: "🇨🇩", fifaRanking: 46, confederation: "CAF",
    coach: "Sébastien Desabre", wcAppearances: 2, bestFinish: "Group Stage (1974)",
    wcRecord: { w: 0, d: 0, l: 3 },
    squad: [
      { name: "L. Moris", pos: "GK", club: "RFC Seraing", num: 16 },
      { name: "C. Luyindama", pos: "DEF", club: "Galatasaray", num: 5 },
      { name: "S. Mbemba", pos: "DEF", club: "Marseille", num: 4 },
      { name: "Y. Wissa", pos: "FWD", club: "Brentford", num: 11 },
      { name: "C. Bakambu", pos: "FWD", club: "Real Betis", num: 9 },
      { name: "A. Banza", pos: "FWD", club: "Braga", num: 7 },
    ],
  },
  GHA: {
    code: "GHA", name: "Ghana", flag: "🇬🇭", fifaRanking: 73, confederation: "CAF",
    coach: "Otto Addo", wcAppearances: 5, bestFinish: "Quarter-finals (2010)",
    wcRecord: { w: 5, d: 4, l: 6 },
    squad: [
      { name: "J. Ati-Zigi", pos: "GK", club: "St Gallen", num: 1 },
      { name: "M. Salisu", pos: "DEF", club: "Monaco", num: 4 },
      { name: "T. Lamptey", pos: "DEF", club: "Brighton", num: 2 },
      { name: "T. Partey", pos: "MID", club: "Arsenal", num: 5 },
      { name: "M. Kudus", pos: "MID", club: "West Ham", num: 10 },
      { name: "I. Williams", pos: "FWD", club: "Athletic Bilbao", num: 9 },
    ],
  },
  RSA: {
    code: "RSA", name: "South Africa", flag: "🇿🇦", fifaRanking: 60, confederation: "CAF",
    coach: "Hugo Broos", wcAppearances: 4, bestFinish: "Group Stage (1998, 2002, 2010)",
    wcRecord: { w: 3, d: 4, l: 6 },
    squad: [
      { name: "R. Williams", pos: "GK", club: "Mamelodi Sundowns", num: 1 },
      { name: "G. Aubaas", pos: "DEF", club: "Young Boys", num: 4 },
      { name: "T. Mokoena", pos: "MID", club: "Mamelodi Sundowns", num: 6 },
      { name: "P. Tau", pos: "FWD", club: "Al-Ahly", num: 11 },
      { name: "E. Mokwena", pos: "FWD", club: "Orlando Pirates", num: 9 },
    ],
  },
  BIH: {
    code: "BIH", name: "Bosnia & Herzegovina", flag: "🇧🇦", fifaRanking: 64, confederation: "UEFA",
    coach: "Sergej Barbarež", wcAppearances: 2, bestFinish: "Group Stage (2014)",
    wcRecord: { w: 1, d: 0, l: 2 },
    squad: [
      { name: "N. Vasilj", pos: "GK", club: "St Pauli", num: 12 },
      { name: "S. Kolašinac", pos: "DEF", club: "Marseille", num: 5 },
      { name: "E. Višća", pos: "MID", club: "Trabzonspor", num: 8 },
      { name: "M. Pjanić", pos: "MID", club: "Sharjah FC", num: 10 },
      { name: "E. Džeko", pos: "FWD", club: "Fenerbahce", num: 9 },
      { name: "E. Demirović", pos: "FWD", club: "Augsburg", num: 11 },
    ],
  },
  CPV: {
    code: "CPV", name: "Cape Verde", flag: "🇨🇻", fifaRanking: 67, confederation: "CAF",
    coach: "Bubista", wcAppearances: 1, bestFinish: "Debut (2026)",
    wcRecord: { w: 0, d: 3, l: 0 },
    squad: [
      { name: "V. Soares", pos: "GK", club: "Portimonense", num: 1 },
      { name: "S. Lopes", pos: "DEF", club: "Nice", num: 4 },
      { name: "N. Borges", pos: "MID", club: "AZ Alkmaar", num: 10 },
      { name: "G. Rodrigues", pos: "MID", club: "Udinese", num: 8 },
      { name: "R. Livramento", pos: "FWD", club: "Gil Vicente", num: 9 },
    ],
  },
};

export function getTeamDetail(code: string): TeamDetail | null {
  return teamDetails[code] || null;
}
